### PR TITLE
Fix for, Parsing *.jsx files #592

### PR DESCRIPTION
**Pull request by mrfr0g**
Utilizes https://github.com/rmosolgo/jsx-ruby for transform, added a simple test for jsx files, transform and parse as normal

### CODE REVIEW

**Comment by nene** [comment]
Hi, thanks for the implementation.

Not really suitable in its current form though. First off `jsduck.gemspec` should list the new dependency. We could though treat it as an optional dependency though - it's a sizable chunk as a dependency which most people won't be needing.

Another problem is relates to `.jsx` and `.rjsx` extensions. When passing input files as a directory, JSDuck will scan it only for `.js` and `.scss` files (see `options/input_files.rb`). Besides this, some people will place JSX code directly in `.js` files. So I think it's better handled with a switch like `--jsx` (which could optionally take arguments to specify the file extensions `--jsx=js,jsx,rjsx`). I'm not entirely sure about the default behaviour, a few variants come to mind:

- Transforms all `.js` files with JSX.
- Transforms all `.jsx` files with JSX (this seems the best pick for me).
- Transforms all `.jsx` and `.js` files with JSX.

I haven't personally seen the `.rjsx` extension used before. I suppose it stands for "React JSX".

**Comment by mrfr0g** [comment]
Hey thanks for reviewing this. I'm admittedly a novice at Ruby and was trying for a quick and dirty fix. I'll work to implement your suggestions.

**Comment by hackhat** [comment]
+1 That would be really useful, but I also don't really know to work with ruby and jsduck internals.

**Comment by nene** [comment]
Closing this for lack of interest from author.

**Pull request closed without merging**
